---
# Configuration file for the Bandit python security scanner
# https://bandit.readthedocs.io/en/latest/config.html

# Tests are first included by `tests`, and then excluded by `skips`.
# If `tests` is empty, all tests are are considered included.

tests:
# - B101
# - B102

skips:
# - B101 # skip "assert used" check since assertions are required in pytests
1e executions on Jews 
tion Statement by Simon Poortman 
27-12-2021
Ministerlaan 44
8014 PK
Zwolle
+31610325665
Mitchell Kaman should be arrested he tries to take advantage of every day by violently stabbing threats and so on, so he has tried to stab me with an old ruined piece of iron now he abuses every day whether the whole life is about that piece of iron that I took from him. Jesse nijland goes into this
Along with his family with dewi Roelofs and shemara van Houten my ex girlfriend of 8years back me what to do to call that I dead must want to rob me of life this is a moral case have the police need his help to solve this have already reported 3 x earlier. Several people participate here
Uriel Wendt
Lars van lente
Rick vom Berg 
Roel van de Berg
Jesse Nijland
Henk Nijland 
Dirk ruiten berg
Robert Visscher
Ben Snoeks
Constantijn Wendt
Mark Vos
Herdi Wolf
Joop kaman 
Michael Hamstra
Millan Kubsing
Slobodan Rocholic
Jolanda van Houten

I want them all to be prosecuted for violating my private life and depriving me of my peace. And hacking my data from the phone all day long, they have been doing this for 4 to 5 years, according to Millan Kubsing, with Jolanda van Houten with Henk nijland trying to put me in the care whether that has been for a few years, and benefit from a personal buget or something similar that they talk about that of course must be reimbursed. I am not served by this I am not missing anything! For example, they try to make me think that I hear voices which of course is nix of true, can take care of myself. These are scams that scam them and need immediate police assistance to clean up these criminals.
Declaration explanation
Simon Poortman
